github:
    full_name:      hiqdev/minii-db

package:
    type:           yii2-extension
    name:           db
    title:          minii DB
    keywords:       minii, db
    namespace:      yii\db
    description:    |
        [minii](https://github.com/hiqdev/minii-core) is mini version of [Yii2](http://yiiframework.com/), supposed to be fully compatible.

        This package provides `yii\db`.

require:
    hiqdev/hidev-php:   "*"
    minii/hidev-vendor: "*"
